# Generated by Django 4.2.2 on 2023-07-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_subdivision_subdivision_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('division', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.division')),
                ('subdivision', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subdivision')),
                ('zone', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.zone')),
            ],
        ),
    ]
